[database]
url = "sqlite+aiosqlite:///./users.db"
echo = true

[auth]
valid_tokens = ["supersecrettoken123", "devtoken456"]
require_api_token = false

[ratelimit]
max_attempts = 5
window_seconds = 10

[server]
host = "0.0.0.0"
port = 8000